### ISSUE TITLE
Add the ability of Query Resources by condition of the Inventory

### ISSUE THREAD

**Issue by walkccc** [NYU-DevOps-Inventory/inventory#45]
**As a** Developer
**I need** Add the ability of Query Resources by condition of the Inventory
**So that** When we are conducting a query on our Inventory, we will be returning a list of records that have the condition specified in the query. 

**Details & Assumptions:** 
* local version of the RESTful service has been completed

**Acceptance Criteria:**

```gherkin
Given the local version of the RESTful service of inventory has been established,
When we call this API
Then the requests will be handled by our application and the query result will be returned.
```

**Comment by eva23511** [comment]
Duplicate with Issue #41
