### ISSUE TITLE
Add Continuous Integration to our repository

### ISSUE THREAD

**Issue by xuezhou1998** [NYU-DevOps-Inventory/inventory#49]
**As a** Developer
**I need** to create a a workflow.yml file and configure Github Actions
**So that** we can run test cases every time someone pushes to the master branch or submits a Pull Request

**Details & Assumptions:** 
* We’ve already defined the tests of our application

**Acceptance Criteria:**

```gherkin
Given Github Actions is configured
When new Pull Request get raised
Then all test cases can be run remotely
```

**Comment by ChingKai5566** [comment]
We are no longer using Travis CI, updating to Github Actions.
